### ISSUE TITLE
v0.6.8 AttributeError: 'str' object has no attribute 'type'

### ISSUE THREAD

**Issue by stevendavis** [jamescasbon/PyVCF#231]
Started seeing this stack trace after upgrading to 0.6.8.  No error when using 0.6.7.

  File .../python2.7/site-packages/vcf/model.py, line 192, in __init__
    self._set_start_and_end()
  File .../python2.7/site-packages/vcf/model.py, line 200, in _set_start_and_end
    elif alt.type == 'SNV':
AttributeError: 'str' object has no attribute 'type'

What am I doing wrong?

**Comment by martijnvermaat** [comment]
Can you give a small sample VCF file which triggers the error?

**Comment by stevendavis** [comment]
The error happens when writing a VCF, not reading.  My code constructs a vcf record before writing it.  You can see the code and the failing unit tests here:

See line 287:
https://github.com/CFSAN-Biostatistics/snp-pipeline/blob/master/snppipeline/vcf_writer.py

**Comment by martijnvermaat** [comment]
The list of alts in `_Record.ALT` should not be plain strings [as you have now](https://github.com/CFSAN-Biostatistics/snp-pipeline/blob/master/snppipeline/vcf_writer.py#L292). This might have worked in 0.6.7, but that's probably by accident.

Instead, they should be instances of `model._AltRecord` ([link](https://github.com/jamescasbon/PyVCF/blob/master/vcf/model.py#L540)). See the `_parse_alt` method ([link](https://github.com/jamescasbon/PyVCF/blob/master/vcf/parser.py#L512)) for an example. I think they should be `None` (not `'.'`) for missing values.

I realize that this is not very convenient. The internal API and models of PyVCF are not always optimized for reuse and especially *writing* has been a bit of an afterthought.

**Comment by stevendavis** [comment]
Thank you for the clarification.  No errors when constructing the _Record with either:
[ _Substitution(base) ] 
or
[ None ]
